export const enum ExceptionCodeName {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_CONFLICT = 'EMAIL_CONFLICT',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD_RESET_TOKEN = 'INVALID_PASSWORD_RESET_TOKEN',
  PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  INVALID_USER_ID = 'INVALID_USER_ID',
}
